# Generated by Django 4.1.1 on 2024-09-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0004_alter_med_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ward_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=120)),
                ('doctor_name', models.CharField(max_length=120)),
                ('Patient_Status', models.CharField(max_length=120)),
                ('Prescription', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=120)),
                ('doctor_name', models.CharField(max_length=120)),
                ('floor_no', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('availability', models.CharField(default=True, max_length=120)),
            ],
        ),
    ]
