# Generated by Django 4.1.1 on 2024-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0005_bed_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='ward_id',
            field=models.CharField(max_length=120),
        ),
    ]
