# Generated by Django 4.1.1 on 2024-09-18 12:18

import Adminsite.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0006_alter_bed_ward_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('medical_history', models.FileField(blank=True, null=True, storage=Adminsite.storage.StaticStorage(), upload_to='')),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('patientpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('appointment_id', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
    ]
