# Generated by Django 4.1.1 on 2024-09-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminsite', '0008_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=100, unique=True)),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule', models.TextField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_id', models.CharField(max_length=100, unique=True)),
                ('drug_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('specialization', models.CharField(default='dentist', max_length=50)),
                ('contact_information', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(default='1234', max_length=100)),
                ('shift_schedule', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
