# Generated by Django 4.1.1 on 2024-09-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='utype',
        ),
    ]
