# Generated by Django 4.1.1 on 2024-09-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_remove_employee_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='utype',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
