# Generated by Django 4.1.1 on 2024-09-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_doctor_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
